#!/bin/bash
#PBS -l walltime=1:30:00
#PBS -l select=1:ncpus=32:mem=10gb
#PBS -N huckel
#PBS -j oe

cd ~/chlorophyll_parameterization/gfn1/

module load lang/python/anaconda/3.8-2020.07

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

python ~/chlorophyll_parameterization/optimizer.py --params k_s k_p --ref_data ~/chlorophyll_parameterization/tddft_data/tddft_data.json --name gfn1_test --gfn gfn1	
