#!/bin/bash
#PBS -l walltime=20:00:00
#PBS -l select=1:ncpus=24:mem=10gb
#PBS -N huckel_global_pair_response_ao_energy_levels
#PBS -j oe

cd ~/chlorophyll_parameterization/fitting_tests/huckel_global_pair_response_ao_energy_levels

module load lang/python/anaconda/3.8-2020.07

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

python ~/chlorophyll_parameterization/optimizer.py --params k_s k_p k_d Mg_s Mg_p Mg_d N_s N_p a_x y_J y_K E_Mg_s E_Mg_p E_Mg_d --ref_data ~/chlorophyll_parameterization/tddft_data/tddft_data.json --name huckel_global_pair_response_ao_energy_levels

