#!/bin/bash -l 
#PBS -l walltime=30:00:00
#PBS -l select=1:ncpus=20:mem=80gb
#PBS -N step_151_chromophore_05
#PBS -j oe

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

cd ~/chlorophyll_parameterization/stda_comparison/step_151_chromophore_05

~/.local/src/Qcore/release/qcore -n 15 -s "step_151_chromophore_05 := excited_scf(structure(file='step_151_chromophore_05.xyz') dft(ansatz=u ao='Def2-SVP' xc=PBE0))" > step_151_chromophore_05_dft_dscf.out
