#!/bin/bash -l 
#PBS -l walltime=30:00:00
#PBS -l select=1:ncpus=20:mem=80gb
#PBS -N step_451_chromophore_16
#PBS -j oe

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

cd ~/chlorophyll_parameterization/stda_comparison/step_451_chromophore_16

~/.local/src/Qcore/release/qcore -n 15 -s "step_451_chromophore_16 := excited_scf(structure(file='step_451_chromophore_16.xyz') dft(ansatz=u ao='Def2-SVP' xc=PBE0))" > step_451_chromophore_16_dft_dscf.out
