#!/bin/bash -l 
#PBS -l walltime=30:00:00
#PBS -l select=1:ncpus=20:mem=80gb
#PBS -N step_501_chromophore_04
#PBS -j oe

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

cd ~/chlorophyll_parameterization/stda_comparison/step_501_chromophore_04

~/.local/src/Qcore/release/qcore -n 15 -s "step_501_chromophore_04 := excited_scf(structure(file='step_501_chromophore_04.xyz') dft(ansatz=u ao='Def2-SVP' xc=PBE0))" > step_501_chromophore_04_dft_dscf.out
