#!/bin/bash
#PBS -l walltime=1:30:00
#PBS -l select=1:ncpus=24:mem=10gb
#PBS -N huckel_electronegativity_kinetic_a_0.0_b_0.0_c_1.0
#PBS -j oe

cd ~/chlorophyll_parameterization/fitting_tests/huckel_electronegativity_kinetic

module load lang/python/anaconda/3.8-2020.07

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

python ~/chlorophyll_parameterization/optimizer.py --params k_s k_p k_d k_EN_s k_EN_p k_EN_d k_T --ref_data ~/chlorophyll_parameterization/tddft_data/tddft_data.json --name huckel_electronegativity_kinetic_a_0.0_b_0.0_c_1.0 --weights 0.0 0.0 1.0

