#!/bin/bash
#PBS -l walltime=20:00:00
#PBS -l select=1:ncpus=24:mem=10gb
#PBS -N huckel_electronegativity_kinetic_response
#PBS -j oe

cd ~/chlorophyll_parameterization/fitting_tests/huckel_electronegativity_kinetic_response

module load lang/python/anaconda/3.8-2020.07

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

python ~/chlorophyll_parameterization/optimizer.py --params k_s k_p k_d k_EN_s k_EN_p k_EN_d k_T a_x y_J y_K --ref_data ~/chlorophyll_parameterization/tddft_data/tddft_data.json

	
