#!/bin/bash -l 
#PBS -l walltime=30:00:00
#PBS -l select=1:ncpus=20:mem=80gb
#PBS -N step_201_chromophore_09
#PBS -j oe

export OMP_NUM_THREADS=1
export MKL_THREADING_LAYER=TBB

cd ~/chlorophyll_parameterization/stda_comparison/step_201_chromophore_09

~/.local/src/Qcore/release/qcore -n 15 -s "step_201_chromophore_09 := excited_scf(structure(file='step_201_chromophore_09.xyz') dft(ansatz=u ao='Def2-SVP' xc=PBE0))" > step_201_chromophore_09_dft_dscf.out
